# Generated by Django 5.1.4 on 2025-05-28 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especialidad',
            options={'verbose_name_plural': 'Especialidades'},
        ),
        migrations.AlterModelOptions(
            name='fichainscripcion',
            options={'verbose_name': 'Ficha de Inscripción', 'verbose_name_plural': 'Fichas de Inscripción'},
        ),
        migrations.AlterModelOptions(
            name='taller',
            options={'verbose_name_plural': 'Talleres'},
        ),
        migrations.AlterField(
            model_name='alumno',
            name='grupo_anterior',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='fichainscripcion',
            name='semestre_inscripcion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fichainscripcion',
            name='taller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registro.taller'),
        ),
        migrations.AlterUniqueTogether(
            name='fichainscripcion',
            unique_together={('alumno', 'semestre_inscripcion')},
        ),
    ]
